### ISSUE TITLE
Fatal Error: Uncaught Error: Class 'NumberFormatter' not found in DashboardPanelNumber.module:43

### ISSUE THREAD

**Issue by jlahijani** [philippdaun/processwire-dashboard#12]
I'm using the latest version of the module on the latest version of ProcessWire.

I created a ```number``` panel and I get this error:
```Fatal Error: Uncaught Error: Class 'NumberFormatter' not found in DashboardPanelNumber.module:43```

I think it's related to this:
https://stackoverflow.com/questions/30554177/fatal-error-class-numberformatter-not-found

Although I could probably fix it by enabling particular things in php.ini and so forth (I'm using php 7.2), a typical LAMP setup does not have that enabled by default which could be problematic for others.

I wonder what your thoughts are.

**Comment by jlahijani** [comment]
Note: running ```sudo apt-get install php7.2-intl``` fixed the issue for me.

**Comment by daun** [comment]
Good catch. I added a fallback formatter that will step in if the `intl` extension is missing.

Could you give the latest release (0.4.13) a try and let me know if it works?
