### ISSUE TITLE
PHP Notice: Undefined variable: trend in .../Dashboard/views/panels/number.php:1

### ISSUE THREAD

**Issue by zoeck-dev** [philippdaun/processwire-dashboard#20]
Hello,

There is a small bug in the "Number" module, the following error is displayed in Tracy:
PHP Notice: Undefined variable: trend in .../Dashboard/views/panels/number.php:1

Fix:
Change the first line in "number.php" to:
`<div class="DashboardPanelNumber__content" data-trend="<?php echo (isset($trend)) ? htmlspecialchars($trend) : ""; ?>">`

**Comment by daun** [comment]
Thanks, fixed in [1.0.1](https://github.com/daun/processwire-dashboard/releases/tag/v1.0.1)
