### ISSUE TITLE
Multisite problem: Dashboard: Filename "" is not in an allowed path.

### ISSUE THREAD

**Issue by spinboxnl** [philippdaun/processwire-dashboard#21]
Getting error _Filename D:/development/cms/site/modules/Dashboard/views/dashboard.php is not in an allowed path_

I'm using a multisite setup. My site modules folders reside in their respective folders **/site-sitename/modules**. I'm not sure, this could be a php related problem but in my case I managed to fix it by replacing the path of the views folder in Dashboard.module:132 (and DashboardPanel.class.php:89). I'd rather not alter the module for updating purposes. Any ideas?

```
$this->viewFolder = __DIR__.'/views/';
```

```
$this->viewFolder = $this->config->paths->siteModules.'Dashboard/views/';
```

And of course; awesome module!

**Comment by daun** [comment]
What OS & PHP version are you on?

The reason I'm using `__DIR__` is that the logic should still work for custom panels that inherit from this base class but live in separate folders. The view folder could be in `site/modules/DashboardPanelLoremIpsum`. I'll take a look at constructing the full path using the `$config` variable.

**Comment by spinboxnl** [comment]
Thanks for your time,

I'm on win10, PHP 7.3.2 .

**Comment by daun** [comment]
Could you download the latest version from the [develop](https://github.com/daun/processwire-dashboard/tree/develop) branch and try it out? I basically only applied your suggested change, but since I never saw the error in the first place, I'd like to make sure it works as expected before tagging a release.

**Comment by spinboxnl** [comment]
This fixes my error from Dashboard.module:132.

I get not found error for DashboardPanel.class.php (Still uses `__DIR__`)

_Wrong path: D:/development/cms/site-bluephoenix2/modules/DashboardPanelNumber/views/panels/number.php_

Applying the same change would result turning this:

```
    public function __construct()
    {
        $this->dashboard = $this->modules->Dashboard;
        $this->viewFolder = __DIR__.'/views/';
    }
```

into:

```
    public function __construct()
    {
        $this->dashboard = $this->modules->Dashboard;
        $this->viewFolder = $this->config->paths->siteModules . $this->dashboard . '/views/';
    }
```

**Comment by daun** [comment]
The predicament here is that

1. the included panels live in the original `/Dashboard/` module folder
2. other third-party panels might live in their own module folders, e.g. `/DashboardPanelHelloWorld/`

Using `__DIR__` was the best way I was aware of to account for both cases. Your proposed fix only works for the first case.

I'll do some experimenting but it might take a few days until I get to it.

**Comment by daun** [comment]
I'm beginning to suspect this is an issue with how I'm using the `wireRenderFile` helper.

Can you put this in your module copy and tell me what it says in the notice?

```php
$this->message('__DIR__: ' . __DIR__ . '/views/');
$this->message('$config: ' . $this->config->paths->siteModules . $this . '/views/');
```

**Comment by spinboxnl** [comment]
Dashboard: __DIR__: D:\development\cms\site\modules\Dashboard/views/ +1
Dashboard: $config: D:/development/cms/site-bluephoenix2/modules/Dashboard/views/

**Comment by daun** [comment]
Thanks, that helps. I'll try a few things in the next days. If patching the files manually works for you now, that's great. I'll just have to make sure the base class stays extensible by standalone modules.

**Comment by spinboxnl** [comment]
Thank you. Of course. Very excited to use it and build a custom panel module.

**Comment by daun** [comment]
Could you try the latest version from the develop branch again? I think this should fix it.

**Comment by spinboxnl** [comment]
Works like a charm. Cheers!
