### ISSUE TITLE
Notice: Undefined variable: content in ..\Dashboard\views\panel.php on line 22 (if empty)

### ISSUE THREAD

**Issue by donatasben** [philippdaun/processwire-dashboard#24]
Hi. Not a huge problem, mostly annoyance while debug mode is on, but still:

If using the **`add-new`** panel type but the "Add pages" (Bookmarks) are empty (none addable exist or user doesn't have permission to add any pages) - it throws a notice:
```
Notice: Undefined variable: content in ..\Dashboard\views\panel.php on line 22
```

For now I just wrapped the whole output in `panel.php` with `<?php if( isset($content) ): ?>` but probably you'll do something more robust.

Was using the simplest call in the `\site\templates\admin.php`:
```
$panels->add([
    'panel' => 'add-new',
    'title' => 'Add new page',
    'data' => [
        'display' => 'list'
    ]
]);
```

**Comment by daun** [comment]
Thanks for the report! This should be fixed on the `develop` branch. Feel free to check it out until I tag the next release on `master`.
