### ISSUE TITLE
PHP Warning: setlocale() expects parameter 1 to be int, string given in DashboardPanelNumber.module:98

### ISSUE THREAD

**Issue by mminglis** [philippdaun/processwire-dashboard#27]
**Describe the bug**
restoreLocales() is passing $category as a string to setlocale when it is set by the line below. These need to be cast to integers.

https://github.com/daun/processwire-dashboard/blob/9a3e0002743460b6c78d1f74b5419ca7fdc102f0/DashboardPanelNumber.module#L93

**Context**
 - PHP version 7.4.21
 - ProcessWire version 3.0.184

**Comment by daun** [comment]
Thanks for reporting. It should be fixed in the latest release. Feel free to reopen the issue if you keep seeing the error.
