### ISSUE TITLE
Missing Edit-Icon in DashboardPanelCollection.module

### ISSUE THREAD

**Issue by flipzoom** [philippdaun/processwire-dashboard#37]
**Describe the bug**
In DashboardPanelCollection.module, the Edit icon is not displayed because a FontAwesome class is specified that does not exist.

**Fix**
Problem is line [#L458](https://github.com/daun/processwire-dashboard/blob/master/DashboardPanelCollection.module#L458). Change from "pen-to-square" to "pencil"

**Context**
Version Dashboard 1.4.0

**Comment by daun** [comment]
Good catch. I'm using Font Awesome Pro for all projects so that one's apparently missing from the free version. I'll think of a good way to find out if the pro version is installed.

**Comment by daun** [comment]
Should be fixed in `1.4.1`.

**Comment by zoeck-dev** [comment]
@daun It's not fixed in 1.4.1 - edit icon still missing
Just use "pencil" :) 

This is working for me:
`'icon'     => ['pen', 'pen-to-square', 'pencil'],`

PW is using Font Awesome 4.7.0, there's no "pen" icon ;)

**Comment by daun** [comment]
@x02a  I pushed a fix that actually checks for existence of icons. Let me know if 1.4.2 is still broken for you.

**Comment by zoeck-dev** [comment]
@daun Thank you, the new version is working again!
