### ISSUE TITLE
Redirect issue after deleting pages from trash

### ISSUE THREAD

**Issue by webmanufaktur** [philippdaun/processwire-dashboard#38]
**Describe the bug**
The dashboard is set to be the start page (/processwire/dashboard/) of ProcessWire (backend). When deleting files from the trash in the page listing (/processwire/page/) a redirect occurs which redirects to the dashboard and therefore doesn't stay on the page listing.

**To Reproduce**
PW Dashboard needs to be set as start page in the backend.
Deleting pages from the trash (which is only available in the page listing /processwire/page/) redirects to the startpage (/processwire/dashboard/).

**Expected behavior**
Deleting pages from the trash (/processwire/page/) 
a) doesn't trigger a redirect (which might be PW specific) or
b) it stays on or redirects to the page listing (/processwire/page/)

**Context**
 - PHP version 7.4
 - ProcessWire 3.0.195
 - Dashboard 1.2.0

**Is it critical?**
No, absolutely not. Just unexpected behaviour. Only ever noticed right now after months and months of using this module.

**Comment by daun** [comment]
I think that's something the dashboard module can't control. I don't know where exactly the redirect is taking place, but I guess the trash process should do some extra work to figure out where to redirect to. If you open an issue on the processwire repo, we might got some input from Ryan on how best to solve this in the core or via module config.

Feel free to reopen if you think there's an obvious fix or a hook we can make use of.
