### ISSUE TITLE
PHP-8.1-related deprecation warning

### ISSUE THREAD

**Issue by Theominator** [philippdaun/processwire-dashboard#49]
Running dashboard under PHP 8.1, there is a deprecation warning:

`Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in ...\site\modules\Dashboard\DashboardPanelCollection.module on line 110`

Could you please fix this? It should be simply by using the null coalescing operator:

`if (strpos($label ?? '', 'fa-') === 0) {`

Thank you and best regards,

Thomas.

**Comment by daun** [comment]
Thanks for reporting. This should be fixed in v1.5.5. Let me know if it isn't.
