### ISSUE TITLE
Tab links aren't responsive

### ISSUE THREAD

**Issue by adrianbj** [philippdaun/processwire-dashboard#51]
**Describe the bug**
Tab list isn't responsive so you can end up with horizontal scrollbar

**To Reproduce**
Add enough tabs / reduce width of viewport enough that they don't fit horizontally

**Expected behavior**
The links should wrap as needed

**Screenshots**
<img width="695" alt="image" src="https://github.com/user-attachments/assets/f7909a97-0a8f-4058-b428-397fb43cf6d9">

**Additional context**
Easily fixed by adding `flex-wrap: wrap;` to https://github.com/daun/processwire-dashboard/blob/7b56b56f60ad12e3ddcd0bc8b59e2bd9d2a649ac/src/Dashboard.css#L240

**Comment by daun** [comment]
Thanks for reporting, I never expected people to use more than one or two of these.

I'm currently travelling and won't be able to make the change for a while — feel free to create a PR with built dist files and I'm happy to merge this one untested :)

**Comment by daun** [comment]
Should be fixed in v1.5.6. Let me know if that solves it for you.

**Comment by adrianbj** [comment]
hi @daun - thanks. Sorry I didn't come back with a PR but in the end I decided I actually needed to make the content of the different tabs load separately (for speed reasons) so I actually replaced the "tabs" with a custom template menu block that loads the page with a `?tab=name` so the content of each tab is loaded on demand as needed.

**Comment by daun** [comment]
Makes sense. I've been meaning to build dynamic tabs into the module myself for some time, but there's only so much time in a day :)
